typography_spectrum: 0.6345543060451746
color:
  brandColors:
    - '#FFFFFF'
    - '#1D1F25'
    - '#CF4A39'
    - '#D97163'
    - '#646870'
  brandStrength: 0.09607504867017269
  lightness: 0.3047164320014417
  saturation: 0.8171794950030744
  rhythmicContrast: 0.6443145119119436
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4488378018140793
analytics:
  google: null
  facebook: null
  twitter: null
name: Yhden
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ABOUT US
    id: b74d089f-dba0-4a45-996b-a47b9a0c42f9
    type: content
favicon: null
title: Yhden
description: Creating global content for international brands
purpose: []
