typography_spectrum: 0.31379
content_rating:
  adult: false
color:
  brandColors:
    - '#242731'
    - '#f1f1f1'
    - '#f45543'
    - '#acaeb1'
    - '#00afdb'
  brandStrength: 0.8316991294268519
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6592677086591721
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74684
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Tom Pattinson
name: Yhden
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ABOUT US
    id: b74d089f-dba0-4a45-996b-a47b9a0c42f9
    type: content
favicon: null
title: Creating global content for international brands
description: ''
purpose: []
