name: Yhden
favicon: null
layout_spectrum: 0.74684
typography_spectrum: 0.43017233558930457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242731'
    - '#f1f1f1'
    - '#f45543'
    - '#acaeb1'
    - '#00afdb'
  brandStrength: 0.8316991294268519
  lightness: 0.5892270593903959
  saturation: 0.8318769275210798
  rhythmicContrast: 0.6592677086591721
purpose: []
