typography_spectrum: 0.31379
color:
  brandColors:
    - '#242731'
    - '#f1f1f1'
    - '#f45543'
    - '#acaeb1'
    - '#00afdb'
  brandStrength: 0.8316991294268519
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6592677086591721
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74684
analytics:
  google: null
  facebook: null
  twitter: null
name: Yhden
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Our Work
    id: 76b9784b-2989-4266-b6e5-edb2621b67b0
    type: content
favicon: null
title: Yhden
description: Creating global content for international brands
purpose: []
